-- SPDX-FileCopyrightText: Iridesium
-- SPDX-License-Identifier: GPL-3.0-only
--
-- The tree: every node of the science path, tiers 3 to 7 (brief §5), as
-- DATA and nothing else. `path.lua` registers the tiers that ship with
-- Progress; `tools/check_tree.py` reads this very file to prove the graph
-- sound and to write docs/history.md, so it stays a plain table literal —
-- one node a line, no code, no locals.
--
-- A node is `id` (the part after `science.`), `tier`, `cost` in insight,
-- `requires` (ids written without a prefix are `science.` nodes), `branch`
-- (the brief's code, named on the Research tab by `config.lua`'s
-- `branches`), `star` when a child can enjoy it, `label`, `text` (the first
-- sentence a child reads, 90 characters at most), `year` (negative before
-- Christ; absent where the world has left history), `source` (who, and
-- where it is written down) and `effects` (integers under `science.*`, read
-- here; `craft.*`, read by Craft; `progress.*`, read by Progress — each
-- summed per player, live).

return {
    -- Tier 3 — Mechanica: antiquity to the Renaissance
    { id = "natural_philosophy", tier = 3, cost = 0, requires = { "shared.fork" }, branch = "MECH", star = true, label = "Natural Philosophy", text = "You turned the dials. Now learn how the world's machines work.", year = -100, source = "the Antikythera Mechanism" },
    { id = "machine_frame", tier = 3, cost = 100, requires = { "natural_philosophy" }, branch = "MECH", star = true, label = "The Machine Frame", text = "Build a frame, put a crank in it, and turn it to make things.", year = -100, source = "the geared devices of Alexandria" },
    { id = "simple_machines", tier = 3, cost = 80, requires = { "natural_philosophy" }, branch = "MECH", star = true, label = "The Five Simple Machines", text = "Lever, wheel, pulley, wedge and screw: five machines, and a crowbar.", year = 60, source = "Hero of Alexandria, Mechanica" },
    { id = "glassworks", tier = 3, cost = 80, requires = { "natural_philosophy" }, branch = "OPTI", label = "The Glassworks", text = "Blow glass into lenses, tubes, jars and bulbs.", year = -50, source = "Syrian glassblowers" },
    { id = "wire_drawing", tier = 3, cost = 80, requires = { "simple_machines" }, branch = "ELEC", label = "Wire Drawing", text = "Pull copper through a drawplate into stock you can carve into wire.", year = 1000, source = "Theophilus, De diversis artibus" },
    { id = "gearing", tier = 3, cost = 100, requires = { "simple_machines", "machine_frame" }, branch = "MECH", star = true, label = "Gear Trains", text = "Shafts and gears carry turning from a wheel to your machines.", year = -250, source = "Philo of Byzantium" },
    { id = "archimedes_screw", tier = 3, cost = 100, requires = { "gearing" }, branch = "MECH", star = true, label = "Archimedes' Screw", text = "Turn a wooden screw and watch the water climb up it.", year = -250, source = "Archimedes, as Vitruvius tells it" },
    { id = "water_wheel", tier = 3, cost = 120, requires = { "gearing" }, branch = "MECH", star = true, label = "The Water Wheel", text = "A wheel in running water turns your machines all day long.", year = -25, source = "Vitruvius, De architectura X" },
    { id = "windmill", tier = 3, cost = 120, requires = { "gearing" }, branch = "MECH", star = true, label = "The Windmill", text = "Sails up high turn in the wind, and faster when it blows hard.", year = 1185, source = "the post mills of England" },
    { id = "stamp_mill", tier = 3, cost = 120, requires = { "water_wheel" }, branch = "METL", label = "The Stamp Mill", text = "Crush ore before you smelt it, and get a third more metal.", year = 1500, source = "the mines of Saxony" },
    { id = "de_re_metallica", tier = 3, cost = 120, requires = { "stamp_mill" }, branch = "METL", label = "De Re Metallica", text = "A miner's book: wash more gold, and pump out flooded shafts.", year = 1556, source = "Georgius Agricola, De re metallica", effects = { { "craft.sluice_gold_period", -3 } } },
    { id = "trip_hammer", tier = 3, cost = 120, requires = { "water_wheel" }, branch = "METL", label = "The Trip Hammer", text = "A hammer the water lifts beats out plates and nails for you.", year = 1200, source = "the forges of Cistercian abbeys", effects = { { "craft.anvil_strikes", -1 } } },
    { id = "blast_furnace", tier = 3, cost = 160, requires = { "water_wheel" }, branch = "METL", label = "The Blast Furnace", text = "Iron ore, charcoal and limestone melt together into pig iron.", year = 1350, source = "the furnaces of the Rhineland" },
    { id = "finery_forge", tier = 3, cost = 120, requires = { "blast_furnace" }, branch = "METL", label = "The Finery", text = "Work pig iron into good wrought iron bars.", year = 1500, source = "the Walloon forges" },
    { id = "cast_iron", tier = 3, cost = 120, requires = { "blast_furnace" }, branch = "METL", label = "Cast Iron", text = "Pour iron into sand moulds for pipes, wheels and plates.", year = 1500, source = "the iron founders of the Weald" },
    { id = "saltpetre_works", tier = 3, cost = 100, requires = { "machine_frame" }, branch = "CHEM", label = "The Saltpetre Men", text = "Soak cave earth and ash to draw out saltpetre.", year = 1550, source = "Vannoccio Biringuccio, De la pirotechnia" },
    { id = "gunpowder", tier = 3, cost = 140, requires = { "saltpetre_works" }, branch = "CHEM", label = "Black Powder", text = "Charges that loosen rock for mining. They never hurt anyone.", year = 1044, source = "the Wujing Zongyao" },
    { id = "escapement", tier = 3, cost = 140, requires = { "gearing" }, branch = "MECH", label = "The Escapement", text = "The tick-tock of the first clocks: machines you can time.", year = 1300, source = "the verge and foliot" },
    { id = "alhazen_optics", tier = 3, cost = 100, requires = { "glassworks" }, branch = "OPTI", star = true, label = "The Book of Optics", text = "A reading stone, and a staff that tells how far, how high, how deep.", year = 1021, source = "Ibn al-Haytham, Kitab al-Manazir" },
    { id = "magnetism", tier = 3, cost = 120, requires = { "natural_philosophy" }, branch = "ELEC", star = true, label = "De Magnete", text = "A dip needle leans toward metal ore hidden in the rock.", year = 1600, source = "William Gilbert, De magnete" },
    { id = "printing_press", tier = 3, cost = 150, requires = { "simple_machines", "cast_iron" }, branch = "AUTO", star = true, label = "The Printing Press", text = "Print what you know, and anyone who reads it learns too.", year = 1440, source = "Johannes Gutenberg" },
    { id = "cementation_steel", tier = 3, cost = 160, requires = { "finery_forge" }, branch = "METL", label = "Blister Steel", text = "Bake iron bars in charcoal for a day and a night, and they turn to steel.", year = 1601, source = "the cementation furnaces of Nuremberg" },

    -- Tier 4 — Natural philosophy, 1600–1760
    { id = "telescope", tier = 4, cost = 180, requires = { "alhazen_optics", "cast_iron" }, branch = "OPTI", star = true, label = "The Telescope", text = "Look at the stars through it, and log every one you find.", year = 1609, source = "Galileo Galilei, Sidereus nuncius" },
    { id = "microscope", tier = 4, cost = 180, requires = { "alhazen_optics" }, branch = "OPTI", star = true, label = "The Microscope", text = "Look very closely at anything and learn what it is made of.", year = 1665, source = "Robert Hooke, Micrographia" },
    { id = "pendulum_clock", tier = 4, cost = 150, requires = { "escapement" }, branch = "MECH", label = "The Pendulum", text = "A swinging weight keeps true time, and every machine runs faster.", year = 1656, source = "Christiaan Huygens", effects = { { "science.machine_speed_percent", 10 } } },
    { id = "chronometer", tier = 4, cost = 200, requires = { "pendulum_clock", "telescope" }, branch = "OPTI", star = true, label = "The Chronometer", text = "Know exactly where you are, and follow a needle to any mark.", year = 1761, source = "John Harrison, H4" },
    { id = "cinnabar_roasting", tier = 4, cost = 150, requires = { "blast_furnace", "glassworks" }, branch = "CHEM", label = "Quicksilver", text = "Roast red cinnabar and catch the liquid silver metal that rises.", year = 1556, source = "Agricola, on the mines of Almaden" },
    { id = "barometer", tier = 4, cost = 180, requires = { "cinnabar_roasting" }, branch = "OPTI", star = true, label = "The Barometer", text = "It tells the weather here, and whether it is coming or going.", year = 1643, source = "Evangelista Torricelli" },
    { id = "thermometer", tier = 4, cost = 150, requires = { "cinnabar_roasting" }, branch = "OPTI", label = "The Thermometer", text = "It reads how warm it is, anywhere you go.", year = 1714, source = "Daniel Gabriel Fahrenheit" },
    { id = "vacuum_pump", tier = 4, cost = 220, requires = { "cast_iron", "glassworks" }, branch = "HEAT", star = true, label = "The Air Pump", text = "Pump the air out of two halves of a ball. Two horses cannot pull them apart!", year = 1654, source = "Otto von Guericke, at Magdeburg" },
    { id = "electrostatics", tier = 4, cost = 200, requires = { "glassworks", "machine_frame" }, branch = "ELEC", star = true, label = "The Friction Machine", text = "Spin a glass globe and it crackles with static charge.", year = 1706, source = "Francis Hauksbee" },
    { id = "leyden_jar", tier = 4, cost = 200, requires = { "electrostatics" }, branch = "ELEC", label = "The Leyden Jar", text = "Keep charge in a jar, to use later.", year = 1745, source = "Pieter van Musschenbroek, Ewald von Kleist" },
    { id = "lightning_rod", tier = 4, cost = 250, requires = { "leyden_jar", "wire_drawing" }, branch = "ELEC", star = true, label = "The Lightning Rod", text = "A copper rod on the highest block catches lightning and fills your jars.", year = 1752, source = "Benjamin Franklin's letters" },
    { id = "franklins_kite", tier = 4, cost = 150, requires = { "lightning_rod" }, branch = "ELEC", star = true, label = "Franklin's Kite", text = "Fly a kite in a storm with a jar in your other hand, and the jar fills.", year = 1752, source = "Benjamin Franklin's letters" },
    { id = "papin_digester", tier = 4, cost = 180, requires = { "cast_iron" }, branch = "HEAT", label = "Papin's Digester", text = "A pressure cooker with a safety valve, for hearty bone broth.", year = 1679, source = "Denis Papin" },
    { id = "newcomen_engine", tier = 4, cost = 280, requires = { "papin_digester", "blast_furnace" }, branch = "HEAT", label = "The Atmospheric Engine", text = "Fire, a boiler and a great beam: the first engine, and a hungry one.", year = 1712, source = "Thomas Newcomen" },
    { id = "coke", tier = 4, cost = 200, requires = { "blast_furnace" }, branch = "METL", label = "Coke", text = "Bake coal into coke, a hotter fuel for the furnace.", year = 1709, source = "Abraham Darby, at Coalbrookdale" },
    { id = "crucible_steel", tier = 4, cost = 250, requires = { "cementation_steel", "coke" }, branch = "METL", label = "Crucible Steel", text = "Melt blister steel in a crucible, and make steel tools.", year = 1740, source = "Benjamin Huntsman" },
    { id = "newtonian_mechanics", tier = 4, cost = 250, requires = { "telescope", "pendulum_clock" }, branch = "GRAV", star = true, label = "Principia", text = "Newton's gravity, and an orrery of the heavens that turns.", year = 1687, source = "Isaac Newton, Principia" },
    { id = "balloon", tier = 4, cost = 180, requires = { "papin_digester" }, branch = "HEAT", star = true, label = "The Montgolfier", text = "A hot-air balloon: rise slowly, and fall softly.", year = 1783, source = "the Montgolfier brothers" },
    { id = "lead_chamber", tier = 4, cost = 200, requires = { "saltpetre_works" }, branch = "CHEM", label = "The Lead Chamber", text = "Make oil of vitriol by the barrel, in a room lined with lead.", year = 1746, source = "John Roebuck" },
    { id = "water_frame", tier = 4, cost = 180, requires = { "water_wheel", "gearing" }, branch = "AUTO", label = "The Water Frame", text = "A water-driven frame spins wool into three times the cloth.", year = 1769, source = "Richard Arkwright" },
    { id = "lathe", tier = 4, cost = 180, requires = { "cast_iron", "water_wheel" }, branch = "MECH", label = "The Powered Lathe", text = "Turn shafts, pistons and bearings on a spinning bed.", year = 1700, source = "the ornamental turners" },

    -- Tier 5 — The Industrial Revolution, 1760–1870
    { id = "watt_engine", tier = 5, cost = 450, requires = { "newcomen_engine", "lathe" }, branch = "HEAT", label = "The Separate Condenser", text = "Watt's engine: twice the power from the same fuel.", year = 1769, source = "James Watt", effects = { { "science.steam_percent", 100 } } },
    { id = "high_pressure_steam", tier = 5, cost = 450, requires = { "watt_engine", "crucible_steel" }, branch = "HEAT", label = "Strong Steam", text = "Small engines of great power.", year = 1800, source = "Richard Trevithick", effects = { { "science.steam_percent", 100 } } },
    { id = "steam_hammer", tier = 5, cost = 400, requires = { "high_pressure_steam" }, branch = "METL", label = "The Steam Hammer", text = "One blow of steam does all an anvil's work.", year = 1839, source = "James Nasmyth", effects = { { "craft.anvil_strikes", -10 } } },
    { id = "puddling", tier = 5, cost = 350, requires = { "coke" }, branch = "METL", label = "Puddling", text = "Stir pig iron in the furnace: two good bars from every pig.", year = 1784, source = "Henry Cort" },
    { id = "bessemer", tier = 5, cost = 500, requires = { "puddling", "high_pressure_steam" }, branch = "METL", label = "The Converter", text = "Blow air through molten iron and it turns to steel in a minute.", year = 1856, source = "Henry Bessemer" },
    { id = "maudslay_lathe", tier = 5, cost = 450, requires = { "lathe", "crucible_steel" }, branch = "MECH", label = "The Screw-Cutting Lathe", text = "Exact screws, springs and bearings, and a jig to build relics.", year = 1800, source = "Henry Maudslay" },
    { id = "interchangeable_parts", tier = 5, cost = 400, requires = { "maudslay_lathe" }, branch = "MECH", label = "Interchangeable Parts", text = "Parts made all alike: every relic takes fewer of them.", year = 1803, source = "Marc Brunel's block mills", effects = { { "science.assembly_parts_percent", -25 } } },
    { id = "jacquard_cards", tier = 5, cost = 400, requires = { "water_frame", "maudslay_lathe" }, branch = "AUTO", star = true, label = "Punched Cards", text = "A card full of holes tells a machine what to make.", year = 1804, source = "Joseph Marie Jacquard" },
    { id = "difference_engine", tier = 5, cost = 550, requires = { "jacquard_cards", "interchangeable_parts" }, branch = "AUTO", label = "The Difference Engine", text = "Babbage's calculating engine: every study teaches you more.", year = 1822, source = "Charles Babbage", effects = { { "progress.study_percent", 20 } } },
    { id = "analytical_engine", tier = 5, cost = 600, requires = { "difference_engine" }, branch = "AUTO", label = "The Analytical Engine", text = "Decks of cards become programs for your automata.", year = 1843, source = "Charles Babbage, Ada Lovelace's Notes" },
    { id = "clockwork_automaton", tier = 5, cost = 600, requires = { "jacquard_cards", "escapement", "maudslay_lathe" }, branch = "AUTO", star = true, label = "The Automaton", text = "A clockwork helper that follows you and carries things.", year = 1774, source = "al-Jazari, Vaucanson, Jaquet-Droz" },
    { id = "voltaic_pile", tier = 5, cost = 400, requires = { "leyden_jar", "lead_chamber" }, branch = "ELEC", label = "The Pile", text = "Stack metals and acid for a steady current, and wires that carry it.", year = 1800, source = "Alessandro Volta" },
    { id = "electrolysis", tier = 5, cost = 450, requires = { "voltaic_pile" }, branch = "CHEM", label = "Electrolysis", text = "Split water and brine with current, and plate one metal with another.", year = 1807, source = "Humphry Davy" },
    { id = "electromagnet", tier = 5, cost = 400, requires = { "voltaic_pile", "wire_drawing" }, branch = "ELEC", star = true, label = "The Electromagnet", text = "Hold a magnet, and dropped things fly to you.", year = 1825, source = "William Sturgeon" },
    { id = "dynamo", tier = 5, cost = 500, requires = { "electromagnet", "watt_engine" }, branch = "ELEC", label = "The Dynamo", text = "Turning makes charge.", year = 1831, source = "Michael Faraday, Experimental Researches" },
    { id = "electric_motor", tier = 5, cost = 450, requires = { "dynamo" }, branch = "ELEC", label = "The Motor", text = "Charge makes turning: any frame on a wire runs.", year = 1834, source = "Moritz von Jacobi" },
    { id = "telegraph", tier = 5, cost = 400, requires = { "electromagnet", "wire_drawing" }, branch = "ELEC", star = true, label = "The Telegraph", text = "Send words down a wire. Tap the key and it clicks!", year = 1837, source = "Samuel Morse" },
    { id = "arc_lamp", tier = 5, cost = 400, requires = { "dynamo" }, branch = "ELEC", star = true, label = "The Arc Lamp", text = "The brightest light there is, while charge feeds it.", year = 1808, source = "Humphry Davy" },
    { id = "cavendish_balance", tier = 5, cost = 450, requires = { "newtonian_mechanics", "maudslay_lathe" }, branch = "GRAV", label = "Weighing the Earth", text = "A needle that points to heavy ore: gold, lead and diamond.", year = 1798, source = "Henry Cavendish" },
    { id = "otis_elevator", tier = 5, cost = 400, requires = { "high_pressure_steam", "crucible_steel" }, branch = "MECH", star = true, label = "The Safety Elevator", text = "A platform that carries you up and down a shaft.", year = 1852, source = "Elisha Otis" },
    { id = "daguerreotype", tier = 5, cost = 400, requires = { "cinnabar_roasting", "electrolysis" }, branch = "OPTI", star = true, label = "The Daguerreotype", text = "Take a picture of a building on a silver plate.", year = 1839, source = "Louis Daguerre" },
    { id = "cyanotype", tier = 5, cost = 500, requires = { "daguerreotype" }, branch = "OPTI", label = "Blueprints", text = "Build a pictured building again, paying for its blocks.", year = 1842, source = "John Herschel" },
    { id = "maxwell", tier = 5, cost = 550, requires = { "dynamo", "telegraph" }, branch = "ELEC", label = "Maxwell's Equations", text = "Light is made of electricity and magnetism.", year = 1865, source = "James Clerk Maxwell" },
    { id = "spectroscope", tier = 5, cost = 400, requires = { "telescope", "glassworks" }, branch = "OPTI", label = "The Spectroscope", text = "Split starlight into colours, and every star teaches you twice.", year = 1859, source = "Gustav Kirchhoff, Robert Bunsen" },
    { id = "dynamite", tier = 5, cost = 400, requires = { "gunpowder", "lead_chamber" }, branch = "CHEM", label = "Dynamite", text = "A stronger charge that loosens even the hardest rock.", year = 1867, source = "Alfred Nobel" },

    -- Tier 6 — The electrical age, 1870–1905, and the aether
    { id = "incandescent_lamp", tier = 6, cost = 700, requires = { "arc_lamp", "vacuum_pump" }, branch = "ELEC", label = "The Incandescent Lamp", text = "A glowing thread in a glass bulb: lamps use far less charge.", year = 1879, source = "Joseph Swan, Thomas Edison", effects = { { "science.lamp_use_percent", -75 } } },
    { id = "polyphase_ac", tier = 6, cost = 900, requires = { "electric_motor", "maxwell" }, branch = "TESL", label = "Alternating Current", text = "Tesla's power lines carry charge right across the world.", year = 1888, source = "Nikola Tesla, US patent 382,280", effects = { { "science.line_loss_percent", -90 } } },
    { id = "transformer", tier = 6, cost = 700, requires = { "polyphase_ac" }, branch = "TESL", label = "The Transformer", text = "Power lines lose half as much.", year = 1885, source = "Zipernowsky, Blathy and Deri", effects = { { "science.line_loss_percent", -50 } } },
    { id = "induction_motor", tier = 6, cost = 800, requires = { "polyphase_ac" }, branch = "TESL", label = "The Induction Motor", text = "Tesla's motor: machines use a quarter less charge.", year = 1888, source = "Nikola Tesla", effects = { { "science.charge_use_percent", -25 } } },
    { id = "tesla_coil", tier = 6, cost = 1000, requires = { "transformer", "leyden_jar" }, branch = "TESL", star = true, label = "The Tesla Coil", text = "Lamps light with no wires, and sparks leap through the air!", year = 1891, source = "Nikola Tesla's lectures" },
    { id = "radio", tier = 6, cost = 900, requires = { "tesla_coil", "maxwell" }, branch = "TESL", star = true, label = "Wireless", text = "Send a message to every radio in the world, with no wire at all.", year = 1893, source = "Nikola Tesla, Guglielmo Marconi" },
    { id = "teleautomaton", tier = 6, cost = 900, requires = { "radio", "clockwork_automaton" }, branch = "AUTO", label = "The Teleautomaton", text = "Tell your automata what to do by radio, from anywhere.", year = 1898, source = "Nikola Tesla's radio boat", effects = { { "science.automata", 2 } } },
    { id = "crookes_tube", tier = 6, cost = 800, requires = { "vacuum_pump", "transformer" }, branch = "TESL", label = "The Crookes Tube", text = "Strange rays glow in a tube with no air in it.", year = 1875, source = "William Crookes" },
    { id = "x_rays", tier = 6, cost = 900, requires = { "crookes_tube" }, branch = "TESL", star = true, label = "X-Rays", text = "See ore glowing through the rock in front of you.", year = 1895, source = "Wilhelm Rontgen" },
    { id = "radioactivity", tier = 6, cost = 900, requires = { "x_rays" }, branch = "CHEM", label = "Radium", text = "Refine pitchblende into radium, which makes charge for ever.", year = 1898, source = "Henri Becquerel, Marie and Pierre Curie" },
    { id = "helium", tier = 6, cost = 800, requires = { "radioactivity", "spectroscope" }, branch = "CHEM", label = "Helium", text = "A gas lighter than air, hidden in pitchblende.", year = 1895, source = "William Ramsay" },
    { id = "tesla_oscillator", tier = 6, cost = 1000, requires = { "induction_motor", "steam_hammer" }, branch = "TESL", star = true, label = "The Earthquake Machine", text = "Tesla's oscillator shakes a whole column of rock loose.", year = 1898, source = "Nikola Tesla" },
    { id = "arc_furnace", tier = 6, cost = 900, requires = { "polyphase_ac" }, branch = "METL", label = "The Arc Furnace", text = "Melt chromium ore with an electric arc, for chrome steel tools.", year = 1900, source = "Paul Heroult" },
    { id = "diamond_drill", tier = 6, cost = 1000, requires = { "arc_furnace", "tesla_oscillator" }, branch = "METL", label = "The Diamond Drill", text = "An electric drill with a diamond tip.", year = 1863, source = "Rodolphe Leschot" },
    { id = "wardenclyffe", tier = 6, cost = 1200, requires = { "tesla_coil", "radio", "polyphase_ac" }, branch = "TESL", star = true, label = "Wardenclyffe", text = "Tesla's great tower sends power to every receiver in the world.", year = 1901, source = "Nikola Tesla, Wardenclyffe Tower" },
    { id = "bakelite", tier = 6, cost = 700, requires = { "coke", "electrolysis" }, branch = "CHEM", label = "Bakelite", text = "The first plastic, made from coal tar: better wires and cases.", year = 1907, source = "Leo Baekeland", effects = { { "science.line_loss_percent", -25 } } },
    { id = "luminiferous_aether", tier = 6, cost = 1000, requires = { "maxwell", "x_rays" }, branch = "GRAV", star = true, label = "The Aether Drift", text = "Here the world leaves history: the aether is real, and it rings.", year = 1887, source = "Michelson and Morley, who found nothing; here they find it" },
    { id = "aether_cell", tier = 6, cost = 1000, requires = { "luminiferous_aether", "radioactivity" }, branch = "GRAV", label = "The Aether Cell", text = "A cell that trickles charge for ever and ever." },
    { id = "cavorite", tier = 6, cost = 1200, requires = { "luminiferous_aether", "helium" }, branch = "GRAV", star = true, label = "Cavorite", text = "A metal that gravity cannot pass through.", year = 1901, source = "H. G. Wells, The First Men in the Moon" },

    -- Tier 7 — Beyond the event horizon
    { id = "gravity_plating", tier = 7, cost = 1500, requires = { "cavorite" }, branch = "GRAV", star = true, label = "Gravity Plating", text = "Stand on cavorite plates and jump as if you were on the Moon." },
    { id = "gravity_well", tier = 7, cost = 1500, requires = { "cavorite", "tesla_coil" }, branch = "GRAV", label = "The Gravity Well", text = "Pull things toward it, or push creatures away." },
    { id = "levitator", tier = 7, cost = 1600, requires = { "gravity_plating", "aether_cell" }, branch = "GRAV", star = true, label = "The Levitator", text = "A harness that lets you fly while its cell has charge." },
    { id = "gravity_engine", tier = 7, cost = 2000, requires = { "gravity_well", "aether_cell" }, branch = "GRAV", label = "The Gravity Engine", text = "Spinning cavorite wheels: the greatest power there is." },
    { id = "stasis_field", tier = 7, cost = 1500, requires = { "gravity_well" }, branch = "GRAV", label = "The Stasis Field", text = "Everything inside it hangs still." },
    { id = "the_core", tier = 7, cost = 3000, requires = { "gravity_engine", "wardenclyffe" }, branch = "FOLD", star = true, label = "The Core", text = "Three rings round a heart of black. It folds space." },
    { id = "wormhole_gates", tier = 7, cost = 2000, requires = { "the_core" }, branch = "FOLD", star = true, label = "Wormholes", text = "Step into one gate and out of its twin, far away." },
    { id = "fold_to_stars", tier = 7, cost = 3000, requires = { "the_core", "spectroscope", "chronometer" }, branch = "FOLD", star = true, label = "The Fold", text = "Fold space to a star, and walk on the world you find there." },
    { id = "terraforming", tier = 7, cost = 2000, requires = { "fold_to_stars", "bessemer" }, branch = "FOLD", label = "Terraforming", text = "Turn a bare world green, one patch at a time." },
    { id = "atmosphere_processor", tier = 7, cost = 1800, requires = { "terraforming" }, branch = "FOLD", label = "The Atmosphere Processor", text = "Give a living world a sky of its own." },
    { id = "the_deep", tier = 7, cost = 2500, requires = { "the_core" }, branch = "FOLD", label = "The Deep", text = "A fold gone wrong: somewhere that is not anywhere." },
    { id = "strange_matter", tier = 7, cost = 2000, requires = { "the_deep" }, branch = "FOLD", label = "Strange Matter", text = "Refine the strange stuff you bring back from the Deep." },
    { id = "recall_beacon", tier = 7, cost = 1500, requires = { "wormhole_gates" }, branch = "FOLD", star = true, label = "The Recall Beacon", text = "Fold yourself home to your own gate, once an hour." },
    { id = "gravitic_drones", tier = 7, cost = 1800, requires = { "teleautomaton", "levitator" }, branch = "AUTO", star = true, label = "Gravitic Automata", text = "Automata that fly: scouts and carriers." },
    { id = "unified_field", tier = 7, cost = 4000, requires = { "the_core", "strange_matter", "fold_to_stars", "terraforming" }, branch = "FOLD", star = true, label = "The Unified Field", text = "Tesla's last theory, finished: fold to any place you have been." },
}
